2024-12-09 16:24:53.272936: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-09 16:24:53.284679: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1733779493.297025 2588678 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1733779493.300804 2588678 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-09 16:24:53.318023: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at /opt/models/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
  0%|          | 0/144 [00:00<?, ?it/s]  4%|▍         | 6/144 [00:00<00:02, 59.18it/s]  8%|▊         | 12/144 [00:00<00:02, 52.95it/s] 12%|█▎        | 18/144 [00:00<00:02, 51.82it/s] 17%|█▋        | 24/144 [00:00<00:02, 51.16it/s] 21%|██        | 30/144 [00:00<00:02, 50.83it/s] 25%|██▌       | 36/144 [00:00<00:02, 50.70it/s] 29%|██▉       | 42/144 [00:00<00:01, 51.10it/s] 33%|███▎      | 48/144 [00:00<00:01, 51.20it/s] 38%|███▊      | 54/144 [00:01<00:01, 50.34it/s] 42%|████▏     | 60/144 [00:01<00:01, 51.14it/s] 46%|████▌     | 66/144 [00:01<00:01, 50.78it/s] 50%|█████     | 72/144 [00:01<00:01, 49.96it/s] 54%|█████▍    | 78/144 [00:01<00:01, 49.62it/s] 58%|█████▊    | 83/144 [00:01<00:01, 49.55it/s] 62%|██████▏   | 89/144 [00:01<00:01, 49.92it/s] 66%|██████▌   | 95/144 [00:01<00:00, 50.58it/s] 70%|███████   | 101/144 [00:01<00:00, 49.54it/s] 74%|███████▍  | 107/144 [00:02<00:00, 49.82it/s] 78%|███████▊  | 113/144 [00:02<00:00, 49.93it/s] 82%|████████▏ | 118/144 [00:02<00:00, 49.82it/s] 85%|████████▌ | 123/144 [00:02<00:00, 49.19it/s] 89%|████████▉ | 128/144 [00:02<00:00, 49.20it/s] 92%|█████████▏| 133/144 [00:02<00:00, 48.44it/s] 97%|█████████▋| 139/144 [00:02<00:00, 49.27it/s]/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
100%|██████████| 144/144 [00:02<00:00, 49.86it/s]
/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Traceback (most recent call last):
  File "/home/2021/kturan/courses/COMP551/COMP-551-A4/jobs/../python/BERT_experiments/over_epochs.py", line 417, in <module>
    plt.plot(epoch_list, f1s, label="F1 Score")
  File "/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/matplotlib/pyplot.py", line 3794, in plot
    return gca().plot(
           ^^^^^^^^^^^
  File "/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/matplotlib/axes/_axes.py", line 1779, in plot
    lines = [*self._get_lines(self, *args, data=data, **kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 296, in __call__
    yield from self._plot_args(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/env_dirs/fall2024/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 486, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (9,) and (1,)
